### ISSUE TITLE
Proposal for medical/health/lifesci vocab covering US Healthcare insurance networks

### ISSUE THREAD

**Issue by danbri** [schemaorg/schemaorg#1062]
This issue tracks a proposal from David Pourtnoy et al. There is a public Google doc at https://docs.google.com/document/d/1LNew5OEon4uir2D5Zzp0AkUPA7c9nO8reJ_M1pOy-3s/edit?usp=gmail

We should note that the design is explicitly US-centric, and that this can be accommodated within schema.org through our 'hosted extensions' mechanism.

@vholland worked on a draft design last year. This has been somewhat discussed alongside the ongoing work on cleanup of existing schema.org medical/health vocabulary (#492) but note that it is a distinct project, even if it is ultimately published within the same extension (e.g. under health-lifesci.schema.org).
# Background (from @dportnoy)

> In November 2015, the US health agency Centers for Medicare & Medicaid Services (CMS) enacted a new regulatory requirement for health insurers who list plans on insurance marketplaces. They must now publish a machine-readable version of their provider network directory, publish it to a specified JSON standard, and update it at least monthly. Many major health insurance companies across the US have already started to publish their health plan coverage, provider directories and drug formularies to this standard.

"This schema is well-defined, required by U.S. government regulation, and is already in use.  So Version 1.0 should be as close to **identical** to the official schema that the CMS agency requires as Schema.org would allow."
- **Official schema:** https://github.com/CMSgov/QHP-provider-formulary-APIs
- **Background:** Explanation of how schema is used: https://www.cms.gov/CCIIO/Resources/Data-Resources/marketplace-puf.html
- **Usage:** As of 3/1/2016, U.S. health plans that participate in insurance markeplaces have published:
  - ~250 health plans
  - ~26,000 URLs describing insurance coverage, provider networks, drug formularies

**Comment by twamarc** [comment]
We should maybe think about a  health insurance vocabulary with the terms used across various insurance providers not only healthcare insurance. For healthcare specificity this would not be many terms as they just use the diseases terminology/coding systemes (like ICDxx, CPT, etc) together with few linking properties (btw some of them we found in schema.org/Offer). The US seems very specific but am sure we can find convergence with europeans plans

~Marc

**Comment by westurner** [comment]
Just lobbing notes over for a tangential (?) use case (and links to links) from https://westurner.org/opengov/us/index#healthcare-gov-hhs-cmms (2015-02) (... https://westurner.org/redditlog/#comment/c93pfhx (2013-03)

> Healthcare.gov (HHS CMMS)⬅
> 
> Homepage: https://www.healthcare.gov/
> Wikipedia: https://en.wikipedia.org/wiki/HealthCare.gov
> Docs: https://www.healthcare.gov/developers/
> Twitter: https://twitter.com/HealthCareGov
> - [ ] TODO: create RDFa vocabulary for health plans
> - [ ] TODO: add RDFa to individual plan pages
> - [ ] TODO: search engine to index RDFa vocabulary
> - [ ] TODO: encourage carriers to add RDFa to describe their servcies

**Comment by twamarc** [comment]
Interesting! Keep it up and keep us posted. thanks @westurner

**Comment by westurner** [comment]
nope, that's just talk.

these look great, thanks!

**Comment by dportnoy** [comment]
This schema is well-defined, required by U.S. government regulation, and is already in use.  So Version 1.0 should be as close to **identical** to the official schema that the CMS agency requires as Schema.org would allow.
* **Official schema:** https://github.com/CMSgov/QHP-provider-formulary-APIs
* **Background:** Explanation of how schema is used: https://www.cms.gov/CCIIO/Resources/Data-Resources/marketplace-puf.html
* **Usage:** As of 3/1/2016, U.S. health plans that participate in insurance markeplaces have published:
   * ~250 health plans
   * ~26,000 URLs describing insurance coverage, provider networks, drug formularies

**Comment by danbri** [comment]
Thanks for the useful background David. I'll copy that into the issue description above too.

**Comment by henryweimd** [comment]
Hi there! Scrubbing in. :)

I really like the Benefits sub-type -- an optional section but critical nontheless.

In the U.S., there are two areas of use cases of relevance:

1. Flagging the tier of the network of the provider (preferred status, often meaning a discount to the consumer)

2. Signalling the availability of secure electronic health messaging as in HHS's Standards & Interoperability work here.  http://wiki.siframework.org/Provider+Directories 

Thanks,
Henry

**Comment by danbri** [comment]
This is published in pending.schema.org, therefore leaving issue open for ongoing discussion.

**Comment by dportnoy** [comment]
Location of latest pending Schema.org for reference, based on CMS/CCIIO mandated QHP schema:

- http://pending.webschemas.org/HealthInsurancePlan
- http://pending.webschemas.org/HealthPlanNetwork
- http://pending.webschemas.org/HealthPlanFormulary
- http://pending.webschemas.org/HealthPlanCostSharingSpecification


@henryweimd, feel free to weigh in

**Comment by Glen-Skelton** [comment]
would it be possible to allow MedicalOrganization, or the specific types of Dentist, Hospital, Pharmacy, or Physician to show acceptance of HealthInsurancePlan or HealthPlanNetwork as a property?

**Comment by westurner** [comment]
> would it be possible to allow MedicalOrganization, or the specific types of Dentist, Hospital, Pharmacy, or Physician to show acceptance of HealthInsurancePlan or HealthPlanNetwork as a property?

How should these edges between {MedicalOrganizations,} and {HealthInsurancePlan, HealthPlanNetwork} indicate {datePublished, effectiveDate}?

- CreativeWork has dateCreated, dateModified, and datePublished

**Comment by westurner** [comment]
> Location of latest pending Schema.org for reference, based on CMS/CCIIO mandated QHP schema:


- "CMS/CCIIO mandated QHP schema:"
  - https://github.com/CMSgov/QHP-provider-formulary-APIs
    - "index.json, plans.json, providers.json, and drugs.json"
  - https://github.com/CMSgov/QHP-provider-formulary-APIs/blob/master/data/plans.json ##
    - ... The JSON-LD example for {HealthInsurancePlan, HealthPlanFormulary, HealthPlanCostSharingSpecification,}: http://pending.webschemas.org/HealthInsurancePlan#examples ##
  - https://github.com/CMSgov/QHP-provider-formulary-APIs/blob/master/data/providers.json

.

- https://www.cms.gov/CCIIO/Resources/Data-Resources/
  - https://www.cms.gov/CCIIO/Resources/Data-Resources/health_plan_finder_data.html

**Comment by thadguidry** [comment]
@mfhepp I think we need to step back and realize that there is a need for acceptedPaymentMethods above the level of Offer and that can also help @westurner answer his questions.

I think often that consumers are worried or wondering if an Organization allows for an acceptable form of payment.  https://schema.org/acceptedPaymentMethod  But this is not only an issue with MedicalOrganizations but anywhere you have a monetary transaction.  We can probably tackle the question more broadly and simply at the Organization level for smaller organizations...."this Org accepts Cash, Credit, Aetna, or BlueCrossBlueSheild"  ...but for larger organizations each particular Service Offered might want to have different AcceptablePaymentMethods ?

@mfhepp There's the need to handle simple cases better for small organizations like a Chinese Restaurant that only accepts CASH.  (why even deal with Offer here, that's a pain...ALL of their offers are CASH only, but we have no nice way for developers to code this.)

A complex case, a radiological scan at a medical clinc that only accepts Credit or HealthInsurance {acceptable insurance: "Aetna, BCBS")

@westurner But to answer your question directly, I think just expanding the expected values under https://schema.org/acceptedPaymentMethod and adding "healthinsurance" might work for MedicalOrganizations.

...but I have serious doubts that keeping acceptedPaymentMethod only under Offer (and not also Organization) will be broadly helpful to consumers that do a search for "doctors in my area that accept CheapoCowboys Insurance"

**Comment by henryweimd** [comment]
Probably not quite as elegant as folks think.  Blue Cross Blue Shield sounds as though it's one payment type -- like Visa or Mastercard.  But sadly it's not: it's just a company/organization.  There are literally thousands of unique contracts between US health insurers and hospitals/doctors/providers that the data model needs to support.  The temptation is to say "yeah but let's just try to make it easy first" which is a big technical debt incurred up-front, since insurance contract eligibility isn't just about payment but rather also whether the patient's health plan offers certain agreed-upon discounts for that health care provider.  Think of the discount contract more like thousands of virtual discount clubs where you might get a 5% discount at Hertz depending on your employer or affiliation group, but need a long CDP code to specify that discount.

**Comment by thadguidry** [comment]
@henryweimd Its more simple for the Consumer use case.  There are different use cases.

1.  Data sharing between MedicalOrganization and Insurance Providers (thought that was solved long ago, so don't see the reason for some of what the proposal brings forth, Consumers won't care about some of it)
2. and sharing between those 2 entities and Search Engines / Consumers so that Consumers can make informed decisions.  This issue is talking about use case #1 ...but I am saying there is a use case like # 2 to benefit consumers questions about which MedicalOrganization accepts which HealthInsurance/Plan(s).

If everyone is saying that this proposal will take care of both #1 and #2 .. then great !

**Comment by Glen-Skelton** [comment]
Currently, Hospitals and patients are communicating in the simple form.  i.e. they are advertising that they accept Aetna or Blue Cross, etc… and patients are searching for providers in their area who accept the same.

Examples: https://www.wellspan.org/provider-directory/provider-details/Adnan-Malik-MD-FACC-Cardiology-Gettysburg-PA/11111746

http://doctors.rush.edu/details/1167/ra-id-abdulla-pediatric_cardiology-chicago

I feel Mr. Guidry’s recommendation to add  https://schema.org/acceptedPaymentMethod to Organizations with "healthinsurance" would be more than acceptable for these situations as they are now.

**Comment by henryweimd** [comment]
Thanks.  As a primary care physician as well as a recovering ex-health
insurance executive, I'd be happy to discuss the reality of the situation
live or directly with anyone interested.  While public-facing ads from
doctors and hospitals often try to use the short-hand to clear through
basic higher-level categories of coverage (if you don't take Aetna you're
unlikely to take any of the flavors of Aetna), there are a lot of false
positives happening in the U.S. market now due to this very
misunderstanding.  And well-meaning hospitals will still err on the side of
getting more patients in, even if they can't pay for it.

The user experience as a result is quite terrible -- the patient sees the
provider and gets a bill that their insurer doesn't cover i.e. they have
Aetna but not the specific network that the patient signed up for.  Or the
patient has scheduled an appointment weeks in advance, only to discover the
night beforehand or the day of the visit that they have Aetna, but not the
specific network of the plan.

So again I'd exhort us to find a path that maybe permits both the
bad-answer-early approach, but perhaps a hierarchical schema that then can
accomodate the "real" answer when those data are available, e.g. specific
health plan ID and/or provider network ID, and not the brand of the
overarching company.

Another quick and unnecessary analogy: this is like asking whether a
restaurant has Coke in the southern parts of the United States.  Coke is
generically used to describe all sodas.  In slightly less crazy cases it's
used to describe Coca-Cola products, but then you need to specify Diet Coke
vs regular Coke (e.g. Coca-Cola Classic).  In the case of health insurance,
imagine that Coca-Cola stocked ~100-200 difference lines of soda, all
vaguely similar but surprisingly different when it came to, say, cancer
treatment and other edge cases of low volume but high meaning.

The 80/20 or Pareto rule doesn't always apply well in health care, for the
very issue that health insurance is ideally something that few people have
to use.  So we may need to thinking about design that is robust enough to
handle edge cases because healthcare, itself, is concerned with optimizing
the care for relatively rare edge cases like cancer, mental health,
specialist visits, and so forth, and not the bulk of healthy people who
don't interact with the system other than routine subacute care.

**Comment by LeezaRodriguez** [comment]
I want to remind all that we have yet to make a clear disambiguation between the physician-person  and the physician-organization.  Within any physician-organization, the individual physician-persons may or may not participate with an insurance carrier.  There is also the issue of the [NPI number](https://npiregistry.cms.hhs.gov). CMS issues unique separate NPI numbers to the physician person **and** the physician organization.  So, we seriously need to make it crystal clear to webmasters what `Physician` represents.  To refresh:

### In the wild
[ `Physician` ](https://schema.org/Physician )is currently defined at schema.org as an organization/ Physician's office, and not the person.  As I have been saying for some time, there is already questionable/incorrect usage of `Physician` [in the wild](https://github.com/schemaorg/schemaorg/issues/807#issuecomment-144743762).  In fact, some of the most reputable portals and institutions are using `Physician`  in their Physician directory to represent the physician person, instead of  the organization entity. 

Even the example cited above by @Glen-Skelton  for [Dr. Malik](https://www.wellspan.org/provider-directory/provider-details/Adnan-Malik-MD-FACC-Cardiology-Gettysburg-PA/11111746) uses the `Physician` markup when this page is clearly about the physician-person, identification of his MedicalSpecialty, and the organization entities he is associated with.  If there is any doubt, the source code references his [INDIVIDUAL NPI number](https://npiregistry.cms.hhs.gov/registry/provider-view/1699829234), and not an organization NPI.  So, in a nutshell, AFAICT, some webmasters are (incorrectly) using `Physician` to represent the physician-person in their physician directory.

### Insurance and Clinical Trial vocabulary
And it's not just an issue with the scalability of Insurance vocabulary. We will run into this `Physician` person vs organization identity crisis with Clinical Trial vocabulary too.  More details found [here ](https://github.com/schemaorg/schemaorg/issues/280#issuecomment-253915688) about those distinctions, as well as my thoughts of how `MedicalSpecialty` lineage truly starts with the physician person , and not the physician organization. 

### What now?

The chickens have come home to roost ;-)

Are we going to address this via adding a new `Profession` type to the core (ala @thadguidry  [suggestion](https://github.com/schemaorg/schemaorg/issues/1410) and @jarnovandriel's [proposal](https://docs.google.com/document/d/151dHBdBcVJ6cW9uqT3ARrmLDFO9gPPSnh87ed4KC844/edit#heading=h.7vq5hoq3p6xi) ) ,  via [other mechanisms](https://github.com/schemaorg/schemaorg/issues/492#issuecomment-233254224) in the medical extension, or something else?

**Comment by LeezaRodriguez** [comment]
@Glen-Skelton   Individual physicians are being rated all over the web. It is not just their organization entity which is being rated. Promise. 

And in any event, the other issues still hold.

**Comment by westurner** [comment]
What are the use cases here?

Has https://schema.org/includesHealthPlanNetwork D: https://schema.org/HealthInsurancePlan R: https://schema.org/HealthPlanNetwork solved for the use cases?

**Comment by gmackenz** [comment]
Changing to [Closed completed]
