### ISSUE TITLE
 AggregateOffer type triggers error with the Structured Data Testing Tool

### ISSUE THREAD

**Issue by Zinebb** [schemaorg/schemaorg#141]
When trying to debug a case on the Google's FR webmasters forum, I noticed a problem in the schema.org documentation:

The second example in https://schema.org/Offer triggers errors when tested with the Structured Data Testing Tool: http://www.google.com/webmasters/tools/richsnippets?q=uploaded:80050431808bb1e0607ce88eb20d2a05

Is this a markup error or is it a bug in the testing tool?
Should AggregateOffer be added as a type that expects an 'offers' property?

Thanks,
Zineb

**Comment by danbri** [comment]
Fixed in https://github.com/schemaorg/schemaorg/pull/209

**Comment by eldk** [comment]
Hello,
Just test AggregateOffers with offers in https://developers.google.com/structured-data/testing-tool/ with example given in http://schema.org/AggregateOffer second and last exemple (copy/paste the code).

Property offers used with AggregateOffers is still throwing and error : "Nous ne reconnaissons pas la propriété offers pour un objet de type AggregateOffer." or we don't know offers property for a AggregateOffer object'

Is it fix on schema.org last released but not for google structured data testing tool ?

Greatings,

Eric

![google_structured_data_error_aggregate_offer_offers](https://cloud.githubusercontent.com/assets/11083657/6279940/e6dfce7a-b8a6-11e4-9df9-f9f7b3e2d52c.jpg)
