### ISSUE TITLE
Support finer-grained distinctions around NewsArticle [and news content]

### ISSUE THREAD

**Issue by danbri** [schemaorg/schemaorg#1525]
There is interest (e.g. from [The Trust Project](http://thetrustproject.org/), and conversations around fact checking and our ClaimReview markup #1061) in using schema.org to describe more detailed kinds of NewsArticle, such as allowing sites to express that an article is an opinion piece, a backgrounder document, analysis, visualization, or that it is sponsored content.  We have also touched on these themes here recently when discussing the idea of a 'Satirical News Article' subtype, see #1437.

See also https://www.theatlantic.com/technology/archive/2017/05/what-people-really-want-from-news-organizations/526902/

In the simplest case we could overload the "genre" property here, but I'd suggest (repeating myself from #1437) that a bit more structure will be more rewarding in terms of markup usability / quality. We could use a simple Enumeration list but I lean towards types since they can be instantiated (to carry properties) and even subtyped further. More compellingly, in the (increasingly popular) JSON-LD format, markup for types is simple, and even multiple types also a simple array of short tokens, whereas in general our markup for enumerated property values involves full URLs and is more error prone.

Update (May 10th) from @danbri:

Several results of these investigations:

 * Proposed new definition of NewsArticle to replace "A news article".
 * Added several (pending) subproperties of http://schema.org/publishingPrinciples
 * Tweak to publishingPrinciples - see #1601 - to allow organizations/persons directly.
 * New subtypes for NewsArticle, again pending: AnalysisNewsArticle, BackgroundNewsArticle, ReportageNewsArticle, OpinionNewsArticle, ReviewNewsArticle.
 * New Article types alongside NewsArticle: SponsoredContentArticle, SatiricalArticle.
 * A "News overview" document describing these, http://webschemas.org/docs/news.html

**Comment by thadguidry** [comment]
So we covered a bit of this before with rNews and how they basically use Genre property for this currently.
But then I think again about some benefits/cons you mention and then think about @rvguha proposal of Compositional Terms / Types #1493 and feel much better about expanding types when/where there would be wide agreement.  I think in the news domain, this would get wide agreement.  But in the end....its still just taking Article and slapping a genre on its back.

So what we are REALLY trying to do here, is basically making it easier for any heavy markup publishers... like news organizations.  And saying that "its OK and beneficial to break norms and add some useful types for this heavy markup domain instead of properties"

So... +1  for expanding typing for News domain.

**Comment by danbri** [comment]
@thadguidry this would be more a Compositional Terms matter if we were trying for FootballNewsArticle, CricketNewsArticle, {huge-list-of-every-sport-enumerated}NewsArticle. The current situation in the news industry is rather different; different kinds of articles are distinguished within the publishing organizations but they are forced by schema.org to call a lot of quite varying things "news articles" due to our lack of detail.  The "genre" field, like "keywords" is certainly a workaround, put then we'd end up pushing everything down into a tagging-like structure.

I'll post a draft for discussion shortly...

**Comment by thadguidry** [comment]
@danbri it still can apply to the Compositional use case... SatiricalNewsArticle ... versus FootballNewsArticle.  But I guess your saying its not about "MainSubject"

1. "MainSubject" NewsArticle ... like the FootballNewsArticle
but more about
2. "KindofNewsArticle" NewsArticle ... like a SatiricalNewsArticle

I'm just pointing out that... both 1 and 2 can get very similar for a lot of publishers so you want to make that very clear as I did above...that this is not about easier typing for Subject composition, but instead for Genre composition :)

**Comment by danbri** [comment]
I agree that making usecases very clear for publishers would be critical here. I'd like to float some designs in our "pending" area (as we did quite successfully with ClaimReview for fact checking) and get their feedback.

**Comment by thadguidry** [comment]
@danbri Updated:  read my last clarity sentence above please and answer that.

**Comment by danbri** [comment]
Yes, subjects would still be described with properties.

**Comment by thadguidry** [comment]
@danbri OK.  Well, here is a Genre visualization URL on what currently passes along the NewsML wires as being a sameAs subType of Article... and just seeing now some of the NewsCodes being used and traveling across Reuters alone, makes me scratch my head...lol... 

http://show.newscodes.org/index.html?newscodes=genre&lang=en-GB&startTo=Show

A few good ones make sense for us to add as subtypes...

Advisory
Biography
Interview
Obituary
Opinion
Question and Answer
etc.

While others in that listing, not very good candidates for discussion to add as a subtype of Article...and are clearly much more of a pure Genre or even Subject.

History
Music
Quote
Raw Sound
etc.

```
From https://iptc.org/standards/newsml-g2/iptc-catalog/

Genre
The <genre> element indicates the style of the content, in this example “interview” as a property that is
distinct from <subject> that is used to indicate the subject matter of content. In the example, an IPTC
Genre NewsCodes value of “Interview” is used:
<genre qcode=“genre:interview”>
<name xml:lang=“en-GB”>Interview</name>
</genre>
```

I also wonder if we need to worry about Media Topic as an additional property and separate issue ?
http://show.newscodes.org/index.html?newscodes=medtop&lang=en-GB&startTo=Show

**Comment by mediaprophet** [comment]
https://en.wikipedia.org/wiki/List_of_genres#Literary_genres (note the list down the side of the page).  I've spent a bit of time looking at this, can't find the reference to that work yet.  

Genre's are not simply for written works: https://www.wikidata.org/wiki/Property:P136 
Classifications have of course been used in libraries for a very long time. 

The problem really gets down to the fact that people who are using wordpress may need simple tools.  A word-press plugin would be ideal, but maybe boolean datatypes would likely be most useful.

**Comment by mediaprophet** [comment]
http://dbpedia.org/page/Non-fiction

**Comment by nicolastorzec** [comment]
**First look and comments:**

- The new, more specific, definition for [NewsArticle](http://webschemas.org/NewsArticle) makes sense :)

- It looks like [NewsArticle](http://webschemas.org/NewsArticle)'s subclasses were designed for tagging purpose since they don't have any specific property, i.e. publishers will have little incentive to use one of the specific classes over the generic one.

- The proposed selection of subclasses for [NewsArticle](http://webschemas.org/NewsArticle) feels incomplete and a bit random: e.g. BackgroundNewsArticle, vs. ReportageNewsArticle, vs. AnalysisNewsArticle. Is there any industry standard with a clear taxonomy and/or guidelines?

- It's not clear which type of news article to use for breaking news and developing articles. We should make it explicit in [NewsArticle](http://webschemas.org/NewsArticle) or in the [News Markup note](http://webschemas.org/docs/news.html)

- [dateline](http://webschemas.org/dateline) is described as "The location where the NewsArticle was produced" but dateline is typically about both the date and place of writing, not just the place.

- We should clarify how to relate a [NewsArticle](http://webschemas.org/NewsArticle) to its categories, topics, and entities: e.g. [this News](https://www.wsj.com/articles/donald-trump-takes-to-twitter-to-defend-firing-james-comey-1494418881) is a _Political_ article about _James Comey_ and _Donald Trump_ while [this other News](http://www.bbc.com/sport/triathlon/39832307) is a _Sport_ article about _Triathlon_, _Ironman 70.3_, and _Alistair Brownlee_. Shall we use [mainEntity](http://schema.org/mainEntity), [genre](http://schema.org/genre), [categories](http://schema.org/categories), etc., ?

- We may want to clarify the distinction between a [SponsoredContentArticle](http://webschemas.org/SponsoredContentArticle) and a [CreativeWork](http://webschemas.org/CreativeWork) that has a [sponsor](http://webschemas.org/sponsor)?

- The [News Markup note](http://webschemas.org/docs/news.html) references [BasicNewsArticle](http://webschemas.org/BasicNewsArticle) but it does not resolve.

- In the [News Markup note](http://webschemas.org/docs/news.html), the link to CriticReviews is broken.

**Comment by danbri** [comment]
Thanks for taking a careful look, @nicolastorzec!

 Some of these points will require further work, let me attempt to dispose of the easier parts first...


### Bug fixes

> In the News Markup note, the link to CriticReviews is broken.

Fixed, thanks.

> The News Markup note references BasicNewsArticle but it does not resolve.

Also fixed; also, thanks. This was an earlier name I was trying out called ReportageNewsArticle, but the latter seems a better fit.

### Breaking News articles (vs LiveBlogPosting)

> It's not clear which type of news article to use for breaking news and developing articles. We should make it explicit in NewsArticle or in the News Markup note

There is a brief paragraph on this in the [news](http://webschemas.org/docs/news.html) overview:

> Real-time coverage of breaking news can be described using [LiveBlogPosting](http://webschemas.org/LiveBlogPosting), or for a [BroadcastEvent](http://webschemas.org/BroadcastEvent), use of the [isLiveBroadcast](http://webschemas.org/isLiveBroadcast) property.

It could be that (as we circulate these to a wider audience for review and experimental implementation) we hear of a need to distinguish LiveBlogPosting from some notion of a breaking news article. Let's keep an open mind on that. The news overview might also benefit from more structure, examples and a table of contents.


### Tags or types 

>  It looks like [NewsArticle](http://webschemas.org/NewsArticle)'s subclasses were designed for tagging purpose since they don't have any specific property, i.e. publishers will have little incentive to use one of the specific classes over the generic one.

There are a few aspects to this. In general ontology design it is reasonable to be wary of types that do not come with properties. While that is a fine consideration to bear in mind for Schema.org, there are other considerations that can favour the use of types anyway in our slightly special context:

 * Type-based syntax is often easier for publishers than property/value combinations (and we like to make things easier for publishers).
 * The hierarchy helps data consumers "dumb down" to better known types i.e. NewsArticle or Article, and can allow for subtypes to be drop-in replacements within existing markup structures.
 * Types create attachment points where others might add their own properties, or future additions/extensions to schema.org might add more detail later.

The point about incentives is important, but I think can be decoupled from the data structure question of whether to use types or not. There are various ways in which users and publishers might benefit from these distinctions being expressed in markup. For now these new types are only going into Schema.org's "pending" zone; let's review later this year to see if news publishers and news-related applications find them a good fit.


### Scope and motivation 

- The proposed selection of subclasses for [NewsArticle](http://webschemas.org/NewsArticle) feels incomplete and a bit random: e.g. BackgroundNewsArticle, vs. ReportageNewsArticle, vs. AnalysisNewsArticle. Is there any industry standard with a clear taxonomy and/or guidelines?

The article types (and 'best practice' linking properties) here are based on the findings of [The Trust Project](http://thetrustproject.org),  which I have attempted to adapt to the existing conventions, constraints and vocabulary that we have at schema.org. The Trust Project have been engaging with news publishers extensively in recent months. I had a few calls with Sally and Subbu from that effort, as well as talking with News-related colleagues, to figure out which of their 'indicators' might be most suited to a markup expression.  The TP "[types of work](https://docs.google.com/document/d/1pLUM-JvGDl5NMUNMi2Hl74MnsoBGw_B3cYIAQ8NyO_M/edit)" document is the closest source for these types, and the TP "[best practices](https://docs.google.com/document/d/1jdt4V92XtveciID3TBl79aiwQcYs5uGSDVdN72PGcpw/edit) indicator was the source for the properties. This was not 1:1 but gave a good starting point based on recent industry conversations. For a longer list of standard codes the news overview does mention the [IPTC news genre codes](http://cv.iptc.org/newscodes/genre/), but the list is rather long and since it is expressed as property values the integration into schema.org is weaker (e.g. for Review).

# Need more work

- [dateline](http://webschemas.org/dateline) is described as "The location where the NewsArticle was produced" but dateline is typically about both the date and place of writing, not just the place.

Yes - needs improving. 

- We should clarify how to relate a [NewsArticle](http://webschemas.org/NewsArticle) to its categories, topics, and entities: e.g. [this News](https://www.wsj.com/articles/donald-trump-takes-to-twitter-to-defend-firing-james-comey-1494418881) is a _Political_ article about _James Comey_ and _Donald Trump_ while [this other News](http://www.bbc.com/sport/triathlon/39832307) is a _Sport_ article about _Triathlon_, _Ironman 70.3_, and _Alistair Brownlee_. Shall we use [mainEntity](http://schema.org/mainEntity), [genre](http://schema.org/genre), [categories](http://schema.org/categories), etc., ?

This is a fair point, but also true for scholarly articles, datasets, books and other creative works. We also have [about](http://schema.org/about) and [mentions](http://schema.org/mentions).  Let's try to agree some improved examples, either for the per-term pages or for news.html.

- We may want to clarify the distinction between a [SponsoredContentArticle](http://webschemas.org/SponsoredContentArticle) and a [CreativeWork](http://webschemas.org/CreativeWork) that has a [sponsor](http://webschemas.org/sponsor)?

Yes, good point.

**Comment by danbri** [comment]
(accidentally clicked 'close and comment' instead of 'comment' there, ignore me)

**Comment by danbri** [comment]
@nicolastorzec - I see now that http://schema.org/dateline was not one of the new properties, it has been there since 2011, http://dev.iptc.org/rNews-1-The-NewsItem-Class has "The location where the content was produced.". While that is not a problem with the proposed changes, this does seem like a good moment to improve things.

**Comment by tmarshbing** [comment]
A few comments from me:

- I agree with the comments from @nicolastorzec that I don't see a lot of value in the new classes v. using the genre property. If we want to encourage a simpler set of genres, we could add that guidance to the NewsArticle description to suggest which genres are most commonly used.
- What is the plan for addressing TV/Radio and media? Will that be covered in this proposal before it moves out of pending? It would be good to be consistent across mediums.
- Do we need examples for the different types of articles (regardless of whether we use types or genres)? Or do news publishers already know clearly which one they should use? I am wondering if we should point to some actual news articles as canonical examples of each.
- Why can't we accomplish the same thing as ReviewNewsArticle with multi-typing of NewsArticle and CriticReview?
- The descriptions of correctionsPolicy and diversityPolicy are short and/or circular. It would be good to expand with a detail or two on typical contents of these.
- The description of actionableFeedbackPolicy is confusing to me. What is this trying to capture?

**Comment by nicolastorzec** [comment]
Thanks for the fixes and comments @danbri and @tmarshbing 

Addressing remaining open points below...

## Re: breaking News vs. other types of news articles

I'm fine with using the base type NewsArticle for breaking news but I still see more cons than pros in subclassing it.

Also, it's almost like breaking news should be disjoint from subtypes such as AnalysisNewsArticle, BackgroundNewsArticle, OpinionNewsArticle, ReportageNewsArticle, or ReviewNewsArticle?

IMO, tagging would work better here. We didn't subclass movies and books. Instead, we associate them with genre(s).

I like @tmarshbing 's idea of creating a simple set of genres, and adding guidance to the NewsArticle description to suggest which genres are most commonly used, and linking to examples.

BTW, ReviewNewsArticle is already defined as a subclass of both NewsArticle and CriticReview. The concept of ReviewNewsArticle is weird to me though. Any example? 

## Re: Linking a News article to its key topics and entities

There is confusion between:
* [mainEntity](http://schema.org/mainEntity): primary entity described in some page or other CreativeWork.
* [about](http://webschemas.org/about): subject matter of the content.
* [mentions](http://webschemas.org/mentions): contains a reference to, but is not necessarily about a concept.

We could clarify as:
1. mainEntity is for THE main entity
1. about is for the other key concepts
1. mentions is for anything else mentioned.

But it's still not a great user experience...

## Re: SponsoredContentArticle vs a CreativeWork that has a sponsor?

We should just make clear that [sponsor](http://schema.org/sponsor) should not be used for CreativeWork that are branded content and advertorials.

## Re: dateline

I'm good with the Wikipedia description: "brief piece of text included in news articles that describes where and when the story occurred, or was written or filed though the date is often omitted."

## Re: addressing TV/Radio and media not just written ones...

Good point :)

## Re: correctionsPolicy, diversityPolicy, actionableFeedbackPolicy

Those policy properties should indeed be more explicit, and parallel to each others.

E.g. correctionsPolicy could read "Statement on corrections policy by an Organization, e.g. a NewsMediaOrganization." Example from the Washington Post [here](http://www.washingtonpost.com/wp-srv/guidelines/corrections.html).

I have no idea what actionableFeedbackPolicy is.

**Comment by danbri** [comment]
thanks @nicolastorzec  - quick thought, perhaps we could say that 'mainEntity' is a subproperty of 'about'?

**Comment by nicolastorzec** [comment]
Sure that works.

**Comment by danbri** [comment]
todo: see http://schema.org/Role

**Comment by danbri** [comment]
I've just added AskPublicNewsArticle, to capture the "HELP US REPORT" category from Trust Project, https://docs.google.com/document/d/1pLUM-JvGDl5NMUNMi2Hl74MnsoBGw_B3cYIAQ8NyO_M/edit#bookmark=id.uxjvtxtbtxpn which they've added to their specs after further consultation / discussions.

**Comment by chaals** [comment]
Hmm. I something about the name `AskPublicNewsArticle` seemed and still seems wrong, but I cannot put my finger on it. Perhaps I should be looking for input on the question...

**Comment by RichardWallis** [comment]
I agree with @chaals, the name doesn't seem to make sense.  I had to read the documentation to get a clue what it might be for.

What about `ReqestedFromPublicNewsArticle` as an alternative.

**Comment by danbri** [comment]
Ping  @subbuvincent + @TheTrustProject who may have alternate suggestions.

Let's see if we can find something shortish, natural and intuitive.

I agree that the name is not the most naturally phrased, but AskPublicNewsArticle is both 1.) shorter than RequestedFromPublicNewsArticle and captures that notion that there is some asking happening and that it relates to the public. 

On my reading (perhaps others' intuitions vary), "RequestedFromPublic(NewsArticle)" is problematic because feels like "past tense" and somehow suggests that it is the news article that was the thing requested. Perhaps produced "by popular request" or something?

My understanding of the concept in @thetrustproject 's terms is that core idea is an appeal to the public to help gather (crowdsource) information on some news topic. Sally / Subbu might care to jump in if we're missing any nuance, or suggest other names...

**Comment by RichardWallis** [comment]
I _was_ trying to go for a more concise name - but failed.

`AskingPublicNewsArticle` - is still a little longer but a bit more descriptive of what it is?

**Comment by TheTrustProject** [comment]
@danbri has nicely captured the concept of AskPublicNewsArticle. It's a call to users to offer story ideas, source ideas, clarifications, etc., related to news coverage or a breaking story. We could go to the language the editors working group suggested, which would be HelpUsReportNewsArticle (even longer, I realize!).

**Comment by thadguidry** [comment]
@danbri @RichardWallis @mfhepp Hmm... there might be something here about an "Ask" versus an "Offer" or even an corollary to http://schema.org/instrument.  I would say that perhaps an "Ask" is a prelude sometimes to an Offer or an Action.  Even a close cousin to http://schema.org/AssessAction That's how things sometimes happen in real life, but we don't yet have a generic type for an "Ask" yet.

Later on we might want to actually have that new type "Ask" to hold things like AskPublicNewsArticle, RFC's, etc. to have a place to land Input kind of things themselves.   As a reminder to all, we actually talked briefly about that in https://schema.org/docs/actions.html

Let's work on an "Ask" type along with this please and see how it fits with an RequestForComment RFC, and others.  I would expect that http://schema.org/instrument would expand to "Ask" as well.

**Comment by subbuvincent** [comment]
Just so all of you have news media examples for the HelpUsReport/AskPublic sub-types, here are some. 

Propublica Help Us Investigate Maternal Mortality (there is @type NewsArticle in this page) 
https://www.propublica.org/getinvolved/help-propublica-and-npr-investigate-maternal-mortality

WBUR (Boston's NPR 90.9FM) crowdsourcing insights from the Boston public head of a Nov 2016 charter schools ballot measure report series 
http://www.wbur.org/edify/2016/08/15/mass-charter-school-debate-stories

KALW (SF Local 91.7 FM) callout/crowdsourcing insights from Bay Area citizens ahead of local election reporting 2016
http://kalw.org/post/help-us-report-2016-elections#stream/0

(Please keep in the mind that the Screendoor web-form used on these Asks won't expand on the pages because the deadline has long passed. Disclosure: I was involved with the WBUR and KALW examples)

Last week Vox put a call for citizens to submit ER billing. 
https://erbills.vox.com/  (this is setup as a separate website, but the schema idea does apply).

@danbri @chaals @thadguidry @RichardWallis

**Comment by danbri** [comment]
@thadguidry I see where you're going with that, but I'd suggest here that we resist the urge to try to decompose crowdsourcing requests into some complex expression built from schema.org primitives.  As you say it's possible we might later find some commonalities across existing terms. I'd suggest we think about news publishers making crowdsourcing requests simply as a "common enough kind of a thing" that we can dedicate a term to it, rather than putting that on hold while trying to generalize to all kinds of requests. If you did want to go in that direction you might start with our existing http://schema.org/Question type. 

I believe there's an opportunity through the work that [the Trust Project](http://thetrustproject.org) are doing with newsrooms and journalists, for the proposed NewsArticle subtypes (like this one) to become drop-in replacements in existing news publishing workflows. The more complicated we make it, the harder that simple adoption becomes. Even figuring out what kind of article something is, is a big enough ask, so I'd argue strongly to keep the markup as basic as possible at this stage. Let's give it 6-12 months in "pending" and see how all these terms are looking in practice. If a richer model for describing requests more generally surfaces, of course we can discuss it, but let's not try to cover too much in the first step.  There are so many similiar sounding but different ideas around "asking" that I fear we could get lost in the distinctions, whereas "newspaper article encourages public to comment on topic" seems a reasonably distinct phenomena.

**Comment by jeannieh** [comment]
The follow code below currently checks out perfect with the SDTT for page https://www.propublica.org/getinvolved/help-propublica-and-npr-investigate-maternal-mortality

<script type="application/ld+json">
{
    "@context": "http://schema.org",
    "@type": "NewsArticle",
    "name": "ProPublica",
    "description": "By many measures, the United States has become the most dangerous industrialized country in which to give birth.",
    "image": {
        "@type": "ImageObject",
        "url": "https://assets.propublica.org/images/getInvolved/20170210-maternal-mortality-1200x630.jpg",
        "width": "1200",
        "height": "630" 
    },
    "url": "https://www.propublica.org/getinvolved/help-propublica-and-npr-investigate-maternal-mortality",
    "mainEntityOfPage": "https://www.propublica.org/getinvolved/help-propublica-and-npr-investigate-maternal-mortality",
    "inLanguage": "en_us",
    "headline": "Do You Know Someone Who Died or Nearly Died in Childbirth? Help Us Investigate Maternal Health",
    "keywords": ["many","measures","states","dangerous","country","birth"],
    "dateCreated": "2017-05-30T05:40:41+0000",
    "dateModified": "2017-09-07T22:01:57+0000",
    "datePublished": "2017-02-10T14:00:00+0000",
    "copyrightYear": "2017",
    "author": {
        "@type": "NGO",
        "name": "ProPublica",
        "description": "ProPublica is an independent, non-profit newsroom that produces investigative journalism in the public interest.",
        "url": "https://www.propublica.org",
        "sameAs": ["https://twitter.com/propublica","https://www.facebook.com/propublica","https://en.wikipedia.org/wiki/ProPublica"],
        "image": {
            "@type": "ImageObject",
            "url": "https://assets.propublica.org/2017-pp-open-graph-1200x630.jpg",
            "height": "630",
            "width": "1200" 
        },
        "telephone": "1-212-514-5250",
        "email": "&#105;&#110;&#102;&#111;&#64;&#112;&#114;&#111;&#112;&#117;&#98;&#108;&#105;&#99;&#97;&#46;&#111;&#114;&#103;",
        "address": {
            "@type": "PostalAddress",
            "streetAddress": "155 Avenue of the Americas",
            "addressLocality": "13th Floor",
            "addressRegion": "New York",
            "postalCode": "N.Y. 10013",
            "addressCountry": "US" 
        },
        "logo": {
            "@type": "ImageObject",
            "url": "https://assets.propublica.org/2017-pp-open-graph-1200x630.jpg",
            "height": "630",
            "width": "1200" 
        },
        "location": {
            "@type": "Place",
            "name": "ProPublica",
            "description": "ProPublica is an independent, non-profit newsroom that produces investigative journalism in the public interest.",
            "hasMap": "http://maps.google.com/maps?q=ProPublica%2C+155+Avenue+of+the+Americas%2C+13th+Floor%2C+New+York+N.Y.+10013%2C+US",
            "telephone": "1-212-514-5250",
            "image": {
                "@type": "ImageObject",
                "url": "https://assets.propublica.org/2017-pp-open-graph-1200x630.jpg",
                "height": "630",
                "width": "1200" 
            },
            "logo": {
                "@type": "ImageObject",
                "url": "https://assets.propublica.org/2017-pp-open-graph-1200x630.jpg",
                "height": "630",
                "width": "1200" 
            },
            "url": "https://www.propublica.org",
            "sameAs": ["https://twitter.com/propublica","https://www.facebook.com/propublica","https://en.wikipedia.org/wiki/ProPublica"],
            "geo": {
                "@type": "GeoCoordinates",
                "latitude": "40.725395",
                "longitude": "-74.0048036" 
            },
            "address": {
                "@type": "PostalAddress",
                "streetAddress": "155 Avenue of the Americas",
                "addressLocality": "13th Floor",
                "addressRegion": "New York",
                "postalCode": "N.Y. 10013",
                "addressCountry": "US" 
            } 
        } 
    },
    "copyrightHolder": {
        "@type": "NGO",
        "name": "ProPublica",
        "description": "ProPublica is an independent, non-profit newsroom that produces investigative journalism in the public interest.",
        "url": "https://www.propublica.org",
        "sameAs": ["https://twitter.com/propublica","https://www.facebook.com/propublica","https://en.wikipedia.org/wiki/ProPublica"],
        "image": {
            "@type": "ImageObject",
            "url": "https://assets.propublica.org/2017-pp-open-graph-1200x630.jpg",
            "height": "630",
            "width": "1200" 
        },
        "telephone": "1-212-514-5250",
        "email": "&#105;&#110;&#102;&#111;&#64;&#112;&#114;&#111;&#112;&#117;&#98;&#108;&#105;&#99;&#97;&#46;&#111;&#114;&#103;",
        "address": {
            "@type": "PostalAddress",
            "streetAddress": "155 Avenue of the Americas",
            "addressLocality": "13th Floor",
            "addressRegion": "New York",
            "postalCode": "N.Y. 10013",
            "addressCountry": "US" 
        },
        "logo": {
            "@type": "ImageObject",
            "url": "https://assets.propublica.org/2017-pp-open-graph-1200x630.jpg",
            "height": "630",
            "width": "1200" 
        },
        "location": {
            "@type": "Place",
            "name": "ProPublica",
            "description": "ProPublica is an independent, non-profit newsroom that produces investigative journalism in the public interest.",
            "hasMap": "http://maps.google.com/maps?q=ProPublica%2C+155+Avenue+of+the+Americas%2C+13th+Floor%2C+New+York+N.Y.+10013%2C+US",
            "telephone": "1-212-514-5250",
            "image": {
                "@type": "ImageObject",
                "url": "https://assets.propublica.org/2017-pp-open-graph-1200x630.jpg",
                "height": "630",
                "width": "1200" 
            },
            "logo": {
                "@type": "ImageObject",
                "url": "https://assets.propublica.org/2017-pp-open-graph-1200x630.jpg",
                "height": "630",
                "width": "1200" 
            },
            "url": "https://www.propublica.org",
            "sameAs": ["https://twitter.com/propublica","https://www.facebook.com/propublica","https://en.wikipedia.org/wiki/ProPublica"],
            "geo": {
                "@type": "GeoCoordinates",
                "latitude": "40.725395",
                "longitude": "-74.0048036" 
            },
            "address": {
                "@type": "PostalAddress",
                "streetAddress": "155 Avenue of the Americas",
                "addressLocality": "13th Floor",
                "addressRegion": "New York",
                "postalCode": "N.Y. 10013",
                "addressCountry": "US" 
            } 
        } 
    },
    "publisher": {
        "@type": "Organization",
        "name": "ProPublica",
        "description": "ProPublica is an independent, non-profit newsroom that produces investigative journalism in the public interest.",
        "url": "https://www.propublica.org",
        "sameAs": ["https://twitter.com/propublica","https://www.facebook.com/propublica","https://en.wikipedia.org/wiki/ProPublica"],
        "image": {
            "@type": "ImageObject",
            "url": "https://assets.propublica.org/2017-pp-open-graph-1200x630.jpg",
            "height": "630",
            "width": "1200" 
        },
        "telephone": "1-212-514-5250",
        "email": "&#105;&#110;&#102;&#111;&#64;&#112;&#114;&#111;&#112;&#117;&#98;&#108;&#105;&#99;&#97;&#46;&#111;&#114;&#103;",
        "address": {
            "@type": "PostalAddress",
            "streetAddress": "155 Avenue of the Americas",
            "addressLocality": "13th Floor",
            "addressRegion": "New York",
            "postalCode": "N.Y. 10013",
            "addressCountry": "US" 
        },
        "logo": {
            "@type": "ImageObject",
            "url": "https://assets.propublica.org/2017-pp-open-graph-1200x630.jpg",
            "height": "630",
            "width": "1200" 
        },
        "location": {
            "@type": "Place",
            "name": "ProPublica",
            "description": "ProPublica is an independent, non-profit newsroom that produces investigative journalism in the public interest.",
            "hasMap": "http://maps.google.com/maps?q=ProPublica%2C+155+Avenue+of+the+Americas%2C+13th+Floor%2C+New+York+N.Y.+10013%2C+US",
            "telephone": "1-212-514-5250",
            "image": {
                "@type": "ImageObject",
                "url": "https://assets.propublica.org/2017-pp-open-graph-1200x630.jpg",
                "height": "630",
                "width": "1200" 
            },
            "logo": {
                "@type": "ImageObject",
                "url": "https://assets.propublica.org/2017-pp-open-graph-1200x630.jpg",
                "height": "630",
                "width": "1200" 
            },
            "url": "https://www.propublica.org",
            "sameAs": ["https://twitter.com/propublica","https://www.facebook.com/propublica","https://en.wikipedia.org/wiki/ProPublica"],
            "geo": {
                "@type": "GeoCoordinates",
                "latitude": "40.725395",
                "longitude": "-74.0048036" 
            },
            "address": {
                "@type": "PostalAddress",
                "streetAddress": "155 Avenue of the Americas",
                "addressLocality": "13th Floor",
                "addressRegion": "New York",
                "postalCode": "N.Y. 10013",
                "addressCountry": "US" 
            } 
        } 
    },
    "articleSection": "Lost Mothers",
    "creator": ["Adriana Gallardo"]
}
</script>

**Comment by subbuvincent** [comment]
@jeannieh Did you mean 'following code' meaning the code below your line. 

Yes, if we went with the new sub-type of NewsArticle we are discussing here, one line will change 

from 
"@type": "NewsArticle"

to 
"@type": "HelpUsReportNewsArticle"

or 
"@type": "AskPublicNewsArticle"

Also two more tidbits to just give more info to everyone (@danbri already knows this) 

1 The origin of the words HelpUsReport - the Trust Project type of work indicator protocol guidelines itself, where the Crowdsourcing type call-to-users is defined with the label [Help Us Report](https://docs.google.com/document/d/1pLUM-JvGDl5NMUNMi2Hl74MnsoBGw_B3cYIAQ8NyO_M/edit#bookmark=id.uxjvtxtbtxpn). 

2 The origin for 'Ask' is the usage in this article, see the headline in particular.  A bunch of journalists (including self) wrote in late 2016 and early 2017. 
https://medium.com/@subbuvincent/ask-and-you-shall-receive-the-power-of-crowdsourcing-for-public-radio-7bff4f189607

**Comment by thadguidry** [comment]
@danbri This is why I hate email and comments, because all the subtlety of my voice is just chucked out the window. :)  Re-read my comment and before all of it put the context "IN THE FUTURE WE COULD...".  I didn't say "hold everything", "I hate this idea", "we need to land the ASK type first before everything."  I was merely expanding thoughts for our future.  I'll be sure to preface future comments like that to avoid disruption.

+1 for getting any types that The Trust Project needs.  How's that for my unwavering support even if its not clear enough how deeply I care about journalists and provide a data tool for them like OpenRefine to boot ? :) :)

**Comment by TheTrustProject** [comment]
@thadguidry thanks for your unwavering support. :> It is much appreciated! The care and engagement this community puts into this vocabulary is inspiring.

**Comment by danbri** [comment]
Thanks @thadguidry :)) yeah, email/github misses a lot. I'd hoped I might run into you at the Wikidata conference. Maybe next time?

Ok, so where are we? 

AskPublicNewsArticle, HelpUsReportNewsArticle, AskingPublicNewsArticle, ... any other candidates?

**Comment by thadguidry** [comment]
Let's make it even better, by combining the ideas into...

PublicHelpOnNewsArticle
HelpReportOnNewsArticle

**Comment by danbri** [comment]
Ok, how about "HelpReportOnNewsArticle" - @subbuvincent @TheTrustProject, is that consistent with the TP intent? It is a little verbose, but most NewsArticles won't be of this type. 


I would also like to clarify how general low-key "contact us if you can help with this story" messaging fits in here. My understanding is that some articles are very heavily focussed on the crowdsourcing, but you still often see a smaller message, as an aside, in other kinds of news article. 
 Perhaps in those cases we can take it as given that news organizations are open to being contacted and the important thing is to have their contact information, and to be clear that the contact information is for the newsroom/journalists rather than for the public? Per-article authorship information can also provide more specific contact opportunities too.

**Comment by chaals** [comment]
I am wondering if "we welcome more information" (which is what I think `YetToBeNamedClassOfNewsArticle` is about) is actually a property of things, not a class.

As far as I know Standard and Poor's, Moody's, and some other rating agencies don't actually invite the public to provide their own ratings, while others do... an AccessibilityDescription is likely to be something with this property too. And of course all kinds of `NewsArticle`s, how-tos, and so on.

**Comment by TheTrustProject** [comment]
@danbri Your context description is quite right - journalism has always depended on the public for tips and sources. There's a growing movement, though, among newsrooms to reach out more actively and we heard a strong call for this from our public interviews.

"HelpUsReportOnNewsArticle" is a little off because the call isn't necessary for that _particular_ article, it's for a breaking story, a beat, an area of coverage, etc.  HelpUsReportNewsArticle is a type of news article that calls for the public to help the newsroom report.

**Comment by danbri** [comment]
@chaals how about we do both? Let's add this new type - since crowdsourcing of news articles is a major phenomena, and worth being able to distinguish from the many other situations in which feedback can be sought. But let's also expand the domain of http://schema.org/contactPoint to CreativeWork, which would allow it to be applied to all kinds of documents...

**Comment by subbuvincent** [comment]
@danbri expanding [contactPoint](http://www.bbc.com/news/world-41821923) to CreativeWork is a great idea. 

It adds an anchor directly connected to a practical nuance in crowdsourced journalism. Many newsrooms often separate out a custom email address for e.g. for receiving responses from a form-tool or even a direct email invited from readers. They tend to avoid using the editors@newsroom.com or letters@newsroom.com account for special projects. 
Allowing a contactPoint for a CreativeWork will allow a NewsArticle that is of the type HelpUsReport or AskPublic to additionally markup this custom ContactPoint - when needed. 
(It might not always get used.)

Independently, what is interesting is that the [Actionable Feedback (AF) Trust Indicator](https://docs.google.com/document/d/1jdt4V92XtveciID3TBl79aiwQcYs5uGSDVdN72PGcpw/edit#bookmark=id.a5m94i6d4jld) anyhow requires a special ContactPoint to be identified. And HelpUsReport/Crowdsourcing type callouts will usually run under an AF umbrella/program in a newsroom. So if CreativeWork can have a CP attached, that same AF CP could be reinvoked here too, even in cases where the newsroom is not creating a custom email address/contact for the callout episode. i.e. This adds flexibility to newsroom CMSes.  (Sorry about going off on a detailed Trust Protocol nuance here, but the dots do connect.) 

All in all, a thumbs up. 

Regarding the difference between HelpUsReportNewsArticle and HelpUsReportOnNewsArticle - hope @TheTrustProject distinction in an earlier comment was clear @thadguidry ?

Also please note that vocabulary wise, we were trying for a term like ReportageNewsArticle, AnalysisNewsArticle, OpinionNewsArticle where the first part of the term is kind of a news genre, and the second part 'NewsArticle' is just the major type. 

So HelpUsReport or AskPublic was an effort to verbalise the genre, which does not require an added connector.

**Comment by thadguidry** [comment]
@subbuvincent Yes the distinction is clear.

**Comment by chaals** [comment]
The recent discussion is strengthening my opposition to making a class. The class of NewsArticles we want input on seems to sit badly with articles of different genres.

**Comment by marco-brandizi** [comment]
Hi all, do we need a specific issue to extend the domain of `contactPoint`? I have yet another case where I would need to have CreativeWork in the domain of this property, specifically I need a contact point for [biological studies](https://bioschemas.org/profiles/Study/0.2-DRAFT).

**Comment by baconjulie** [comment]
Are there other valid use cases for OpinionNewsArticle or are there plans to remove it from the documentation if it is not recommended for use?

**Comment by TheTrustProject** [comment]
@baconjulie All the news types you list above are in use by Trust Project news partners. We were advised that "pending" would be eventually lifted. @danbri , can you help?

**Comment by choochatjumpathongcj** [comment]
GDPRSPDRESG GDPRESGGROUP

**Comment by 46009361** [comment]
In support of this. Google Search uses Schema.org and their AI Overview is mistaking satirical articles for real.

https://www.bbc.com/news/articles/cly12egqq5ko

**Comment by jbwhong** [comment]
This seems like the most logical place to make this request.

There is already a "dateline" in schema; however there's evidence that the meaning of a dateline varies from publi[cation to publication (see Julie Moos' article at Poynter in which she found different publications had different meanings.](https://www.poynter.org/reporting-editing/2003/datelines-bylines-other-lines/)). I think that in the interest of transparency and clarity, journalistic organizations may want to publish their datelinePolicy if they use datelines. As an example, the [Associated Press policy on datelines](https://www.ap.org/about/news-values-and-principles/telling-the-story/) explains they use it to say where the basic information was obtained, except on short stories with no byline and on images and audio, in which case it means that's where the news happened. A machine-readable policy could help with determining what a dateline is intended to mean at a specific site and, if someone decides to build a rich results tool, could help people find these policies so they understand better.
